# Generated by Django 5.2.14 on 2026-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('localizacao_atual_equipamento', models.CharField(blank=True, max_length=255, null=True)),
                ('servico_executado', models.TextField(blank=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('backup', models.BooleanField(default=0)),
                ('backup_data', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Em andamento'), (1, 'Finalizado'), (2, 'Não foi possivel realizar manutenção')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
