# Generated by Django 5.2.14 on 2026-05-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamado', '0002_initial'),
        ('equipamento', '0002_initial'),
        ('equipeTecnica', '0002_initial'),
        ('manutencao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='backup_feito_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamado.chamado'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamento.equipamento'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='tecnicos',
            field=models.ManyToManyField(related_name='manutencoes', to='equipeTecnica.tecnico'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['-created_at'], name='manutencao__created_d555eb_idx'),
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['active', 'visible'], name='manutencao__active_b52947_idx'),
        ),
    ]
