# Generated by Django 5.2.14 on 2026-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipeTecnica', '0006_tecnico_cargo'),
        ('manutencao', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, related_name='manutencoes', to='equipeTecnica.tecnico'),
        ),
    ]
