# Generated by Django 5.2.14 on 2026-08-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0005_alter_chamado_status_chamado'),
        ('manutencao', '0003_alter_manutencao_tecnicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='destino_equipamento',
            field=models.IntegerField(blank=True, choices=[(0, 'Em uso'), (1, 'Estoque'), (3, 'Descarte')], null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='chamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='chamado.chamado'),
        ),
    ]
