# Generated by Django 5.2.14 on 2026-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('modelo_equipamento', models.CharField(max_length=255)),
                ('patrimonio', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('numero_de_serie', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('tipo_equipamento', models.IntegerField(choices=[(0, 'Impressora'), (1, 'Computador'), (2, 'Monitor'), (3, 'Telefone')])),
                ('status', models.IntegerField(choices=[(0, 'Em uso'), (1, 'Estoque'), (2, 'Em manutenção'), (3, 'Descarte')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
