# Generated by Django 5.2.14 on 2026-05-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0001_initial'),
        ('unidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='unidade_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unidade.unidade'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['-created_at'], name='equipamento_created_30c99d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['active', 'visible'], name='equipamento_active_db6f3c_idx'),
        ),
    ]
