# Generated by Django 5.2.14 on 2026-06-16 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade', '0017_remove_sala_altura_remove_sala_largura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ramal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('numero', models.CharField(db_index=True, max_length=10)),
                ('setor', models.CharField(help_text='Rótulo do grupo no PABX (ex: OBRAS, JURÍDICO, SAUDE)', max_length=120)),
                ('ocupante', models.CharField(blank=True, help_text='Nome/função; vazio ou "VAGO" = sem ocupante', max_length=150)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('divisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ramais', to='unidade.divisao')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero'],
                'abstract': False,
                'indexes': [models.Index(fields=['-created_at'], name='ramal_ramal_created_3cb04d_idx'), models.Index(fields=['active', 'visible'], name='ramal_ramal_active_e67044_idx')],
            },
        ),
    ]
