# Generated by Django 5.2.14 on 2026-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=155)),
                ('descricao', models.TextField()),
                ('nome_solicitante', models.CharField(max_length=155)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('urgencia', models.IntegerField(choices=[(0, 'Baixa'), (1, 'Média'), (2, 'Alta'), (3, 'Crítica')], default=0)),
                ('status_chamado', models.IntegerField(choices=[(0, 'Aberto'), (1, 'Em andamento'), (2, 'Finalizado')], default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
