# Generated by Django 5.2.14 on 2026-05-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamado', '0001_initial'),
        ('equipamento', '0001_initial'),
        ('equipeTecnica', '0001_initial'),
        ('unidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, related_name='chamados', to='equipamento.equipamento'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='equipes',
            field=models.ManyToManyField(related_name='chamados', through='equipeTecnica.Atendimento', to='equipeTecnica.equipe'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade.unidade'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['-created_at'], name='chamado_cha_created_99f410_idx'),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['active', 'visible'], name='chamado_cha_active_5bcff2_idx'),
        ),
    ]
