# Generated by Django 5.2.14 on 2026-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='tipo_chamado',
            field=models.IntegerField(choices=[(0, 'Helpdesk'), (1, 'Manutenção'), (2, 'Requisição'), (3, 'Suporte')], default=0),
        ),
    ]
