# Generated by Django 5.2.14 on 2026-08-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_chamado_tipo_chamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status_chamado',
            field=models.IntegerField(choices=[(0, 'Aberto'), (1, 'Em andamento'), (2, 'Finalizado'), (3, 'Cancelado')], default=0),
        ),
    ]
