# Generated by Django 5.2.14 on 2026-08-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0007_alter_chamado_status_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='urgencia_manual',
            field=models.BooleanField(default=False, help_text='Urgência definida por uma pessoa — congela o escalonamento automático.'),
        ),
    ]
