# Generated by Django 5.2.14 on 2026-09-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0008_chamado_urgencia_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='agendado_para',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
