# Generated by Django 5.2.14 on 2026-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
