# Generated by Django 5.2.14 on 2026-07-16 13:45

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaDivisao',
            fields=[
            ],
            options={
                'verbose_name': 'Pendência de divisão',
                'verbose_name_plural': 'Pendências de divisão',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='divisao_definida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='obs_importacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
