# Generated by Django 5.2.14 on 2026-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_pendenciadivisao_usuario_divisao_definida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=False),
        ),
    ]
