# Generated by Django 5.2.14 on 2026-07-16 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0017_remove_sala_altura_remove_sala_largura_and_more'),
        ('usuario', '0004_usuario_precisa_trocar_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDivisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Aprovada'), (2, 'Recusada')], default=0)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_entrada', to='unidade.divisao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_divisao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
