"""
Django settings for backendChamados project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Tudo que muda entre a máquina do dev e a VPS vem de variável de ambiente, com
# o valor de desenvolvimento como padrão: rodar `manage.py runserver` local
# continua funcionando sem .env nenhum.

def _env(nome, padrao=''):
    """
    Valor da variável, ou o conteúdo do arquivo apontado por <NOME>_FILE.

    O Swarm entrega segredo como arquivo em /run/secrets/, o compose entrega
    como variável. Aceitar os dois evita manter dois settings — e mantém a
    senha fora da listagem de `docker inspect`, que expõe o environment.
    """
    caminho = os.environ.get(f'{nome}_FILE')
    if caminho:
        with open(caminho, encoding='utf-8') as arquivo:
            return arquivo.read().strip()
    return os.environ.get(nome, padrao)


def _lista_env(nome, padrao=''):
    return [item.strip() for item in _env(nome, padrao).split(',') if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
# Em produção o docker-compose injeta DJANGO_SECRET_KEY — esta abaixo é pública
# (está no repositório) e serve só pro ambiente local.
SECRET_KEY = _env(
    'DJANGO_SECRET_KEY',
    'django-insecure-n54p=7(qdqi7m&rki2nqh-zon0%+zgoj=1_@@ps6e#fc8plsmq',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = _lista_env('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

AUTH_USER_MODEL = 'usuario.Usuario'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "automovel.apps.AutomovelConfig",
    "chamado.apps.ChamadoConfig",
    "equipamento.apps.EquipamentoConfig",
    "equipeTecnica.apps.EquipetecnicaConfig",
    "manutencao.apps.ManutencaoConfig",
    "terceirizada.apps.TerceirizadaConfig",
    "ramal.apps.RamalConfig",
    "rede.apps.RedeConfig",
    "unidade.apps.UnidadeConfig",
    "usuario.apps.UsuarioConfig",
    "core.apps.CoreConfig",
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',          # corsheaders ANTES do CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS — front Vite (5173) e segunda porta quando 5173 está ocupada (5174).
# Em produção a lista fica VAZIA de propósito: o nginx serve SPA e API na mesma
# origem, então não há requisição cross-origin pra liberar.
CORS_ALLOWED_ORIGINS = _lista_env(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174'
    if DEBUG else '',
)
CORS_ALLOW_CREDENTIALS = True   # cookies de session vão entre front e back

# CSRF: o front também precisa estar listado pra POST/PUT/DELETE funcionarem.
# Em produção entram aqui os domínios públicos (com esquema), via .env.
CSRF_TRUSTED_ORIGINS = _lista_env(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174'
    if DEBUG else '',
)

ROOT_URLCONF = 'backendChamados.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backendChamados.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': _env('DB_NAME', 'sistema_chamados'),
        'USER': _env('DB_USER', 'root'),
        'PASSWORD': _env('DB_PASSWORD', 'root'),
        # no compose o host é o nome do serviço ('db'), não localhost
        'HOST': _env('DB_HOST', '127.0.0.1'),
        'PORT': _env('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # SessionAuth sem CSRF enforce — necessário pro SPA cross-origin (ver core/authentication.py)
        'core.authentication.CsrfExemptSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # cargos supervisionados só leem — vale pra toda a API, não só pro menu
        'core.permissions.AprendizSomenteLeitura',
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

# Guardamos tudo em UTC no banco (USE_TZ), mas "hoje", "agora" e o que o admin
# mostra passam a ser no horário de Brasília. Atenção: as tabelas de fuso do
# MySQL não estão carregadas aqui, então lookups __date/__month sobre campos de
# data NÃO funcionam (viram CONVERT_TZ e devolvem NULL) — use core.tempo.
TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# destino do collectstatic; em produção é um volume que o nginx lê direto
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploads (plantas dos prédios, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ---------------------------------------------------------------------------
# Produção atrás do nginx
# ---------------------------------------------------------------------------

# Quem termina o TLS é o nginx; o Django só sabe disso pelo cabeçalho que ele
# repassa (deploy/nginx/proxy_params_chamados).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie 'secure' só quando o domínio já tem certificado: ligado cedo demais,
# o navegador descarta o cookie de sessão em HTTP e ninguém consegue logar.
_HTTPS = os.environ.get('DJANGO_HTTPS', '0') == '1'
SESSION_COOKIE_SECURE = _HTTPS
CSRF_COOKIE_SECURE = _HTTPS

if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_HTTPONLY = True
    X_FRAME_OPTIONS = 'DENY'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
