# Generated by Django 5.2.14 on 2026-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaAutomovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('data_agendamento', models.DateTimeField()),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('tipo_agendamento', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=55)),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('cor', models.IntegerField(choices=[(0, 'Branco'), (1, 'Preto'), (2, 'Cinza')])),
                ('status', models.IntegerField(choices=[(0, 'Disponivel'), (1, 'Manutenção'), (2, 'Em uso')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
