# Generated by Django 5.2.14 on 2026-05-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automovel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaautomovel',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendaautomovel',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automovel',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automovel',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendaautomovel',
            name='automovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='automovel.automovel'),
        ),
        migrations.AddIndex(
            model_name='automovel',
            index=models.Index(fields=['-created_at'], name='automovel_a_created_7832a0_idx'),
        ),
        migrations.AddIndex(
            model_name='automovel',
            index=models.Index(fields=['active', 'visible'], name='automovel_a_active_8b6790_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaautomovel',
            index=models.Index(fields=['-created_at'], name='automovel_a_created_324495_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaautomovel',
            index=models.Index(fields=['active', 'visible'], name='automovel_a_active_eb30c2_idx'),
        ),
    ]
