# Generated by Django 5.2.14 on 2026-06-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovel',
            name='assentos',
            field=models.IntegerField(default=2, help_text='Lugares — define os slots do lobby de equipe'),
        ),
    ]
