# Generated by Django 5.2.14 on 2026-06-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0004_seed_veiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaautomovel',
            name='tipo_agendamento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
