# Generated by Django 5.2.14 on 2026-05-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automovel', '0002_initial'),
        ('chamado', '0002_initial'),
        ('equipeTecnica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipe',
            name='automovel_utilizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipes_utilizadoras', to='automovel.automovel'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='chamado_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipes_atendendo_agora', to='chamado.chamado'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipe',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='equipeTecnica.equipe'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipe',
            name='tecnicos',
            field=models.ManyToManyField(related_name='equipes', to='equipeTecnica.tecnico'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['-created_at'], name='equipeTecni_created_192985_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['active', 'visible'], name='equipeTecni_active_80fac0_idx'),
        ),
        migrations.AddIndex(
            model_name='tecnico',
            index=models.Index(fields=['-created_at'], name='equipeTecni_created_62e3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='tecnico',
            index=models.Index(fields=['active', 'visible'], name='equipeTecni_active_7265a9_idx'),
        ),
        migrations.AddIndex(
            model_name='equipe',
            index=models.Index(fields=['-created_at'], name='equipeTecni_created_990e53_idx'),
        ),
        migrations.AddIndex(
            model_name='equipe',
            index=models.Index(fields=['active', 'visible'], name='equipeTecni_active_23e1b1_idx'),
        ),
    ]
