# Generated by Django 5.2.14 on 2026-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipeTecnica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='responsabilidade',
            field=models.IntegerField(choices=[(0, 'Redes'), (1, 'Infra'), (2, 'Suporte'), (3, 'Despachante'), (4, 'Auditoria')], default=2),
        ),
    ]
