# Generated by Django 5.2.14 on 2026-08-07 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipeTecnica', '0003_alter_tecnico_responsabilidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='responsabilidade',
        ),
        migrations.CreateModel(
            name='ResponsabilidadeTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('responsabilidade', models.IntegerField(choices=[(0, 'Redes'), (1, 'Infra'), (2, 'Suporte'), (3, 'Despachante'), (4, 'Auditoria')])),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsabilidades_set', to='equipeTecnica.tecnico')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['-created_at'], name='equipeTecni_created_8661f5_idx'), models.Index(fields=['active', 'visible'], name='equipeTecni_active_98f7b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('tecnico', 'responsabilidade'), name='unica_responsabilidade_por_tecnico')],
            },
        ),
    ]
