# Generated by Django 5.2.14 on 2026-08-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipeTecnica', '0004_remove_tecnico_responsabilidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsabilidadetecnico',
            name='responsabilidade',
            field=models.IntegerField(choices=[(0, 'Redes'), (1, 'Infra'), (2, 'Suporte'), (3, 'Despachante'), (4, 'Help desk')]),
        ),
    ]
