# Generated by Django 5.2.14 on 2026-08-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipeTecnica', '0005_alter_responsabilidadetecnico_responsabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='cargo',
            field=models.IntegerField(choices=[(0, 'Técnico'), (1, 'Estagiário'), (2, 'Jovem aprendiz')], default=0),
        ),
    ]
