# Generated by Django 5.2.14 on 2026-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipeTecnica', '0007_participacaoequipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsabilidadetecnico',
            name='responsabilidade',
            field=models.IntegerField(choices=[(0, 'Redes'), (1, 'Infra'), (2, 'Suporte'), (3, 'Administrativo'), (4, 'Help desk')]),
        ),
    ]
