# Generated by Django 5.2.14 on 2026-09-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipeTecnica', '0008_alter_responsabilidadetecnico_responsabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='instrucoes_solicitante',
            field=models.TextField(blank=True, default='', help_text='Orientações deixadas pelo técnico para o solicitante ler.'),
        ),
    ]
