# Generated by Django 5.2.14 on 2026-09-04 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0002_initial'),
        ('unidade', '0019_sigla_smgde'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('tipo', models.IntegerField(choices=[(0, 'Roteador'), (1, 'Switch'), (2, 'Access point'), (3, 'Servidor'), (4, 'Impressora'), (5, 'Câmera/DVR'), (6, 'Outro')], default=6)),
                ('nome_na_rede', models.CharField(max_length=100)),
                ('ip', models.CharField(blank=True, default='', max_length=100)),
                ('usuario_acesso', models.CharField(blank=True, default='', max_length=100)),
                ('senha_acesso', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_rede', to='equipamento.equipamento')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_rede', to='unidade.unidade')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unidade__nome', 'tipo', 'nome_na_rede'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedeWifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('ssid', models.CharField(max_length=100)),
                ('senha', models.TextField(blank=True, default='')),
                ('oculta', models.BooleanField(default=False)),
                ('visitantes', models.BooleanField(default=False, help_text='Rede aberta a visitantes (sem acesso interno).')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redes_emitidas', to='rede.dispositivorede')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redes_wifi', to='unidade.unidade')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unidade__nome', 'ssid'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='dispositivorede',
            index=models.Index(fields=['-created_at'], name='rede_dispos_created_541f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivorede',
            index=models.Index(fields=['active', 'visible'], name='rede_dispos_active_7b0a67_idx'),
        ),
        migrations.AddIndex(
            model_name='redewifi',
            index=models.Index(fields=['-created_at'], name='rede_redewi_created_caa55d_idx'),
        ),
        migrations.AddIndex(
            model_name='redewifi',
            index=models.Index(fields=['active', 'visible'], name='rede_redewi_active_e53020_idx'),
        ),
    ]
