# Generated by Django 5.2.14 on 2026-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivorede',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Roteador'), (1, 'Switch'), (3, 'Servidor'), (4, 'Impressora'), (5, 'Câmera'), (6, 'Outro')], default=6),
        ),
    ]
