# Generated by Django 5.2.14 on 2026-05-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaTerceirizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('numero_telefone', models.CharField(max_length=20)),
                ('link_site', models.URLField(blank=True, max_length=255, null=True)),
                ('responsabilidade', models.IntegerField(choices=[(0, 'Telefonia'), (1, 'Impressoras'), (2, 'Computadores'), (3, 'Câmeras'), (4, 'Provedor de Internet')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChamadoTerceirizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=155)),
                ('descricao', models.TextField()),
                ('protocolo', models.CharField(max_length=50)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('status_chamado', models.IntegerField(choices=[(0, 'Aberto'), (1, 'Em andamento'), (2, 'Finalizado'), (3, 'Não resolvido')], default=0)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamado.chamado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
