# Generated by Django 5.2.14 on 2026-05-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceirizada', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadoterceirizada',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamadoterceirizada',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaterceirizada',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaterceirizada',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamadoterceirizada',
            name='empresa_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceirizada.empresaterceirizada'),
        ),
        migrations.AddIndex(
            model_name='empresaterceirizada',
            index=models.Index(fields=['-created_at'], name='terceirizad_created_64bf19_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaterceirizada',
            index=models.Index(fields=['active', 'visible'], name='terceirizad_active_aa632f_idx'),
        ),
        migrations.AddIndex(
            model_name='chamadoterceirizada',
            index=models.Index(fields=['-created_at'], name='terceirizad_created_6cb2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='chamadoterceirizada',
            index=models.Index(fields=['active', 'visible'], name='terceirizad_active_97265e_idx'),
        ),
        migrations.AddConstraint(
            model_name='chamadoterceirizada',
            constraint=models.UniqueConstraint(fields=('protocolo', 'empresa_responsavel'), name='protocolo_por_empresa'),
        ),
    ]
