# Generated by Django 5.2.14 on 2026-06-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_chamado_tipo_chamado'),
        ('terceirizada', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadoterceirizada',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegacoes', to='chamado.chamado'),
        ),
        migrations.AlterField(
            model_name='chamadoterceirizada',
            name='empresa_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='terceirizada.empresaterceirizada'),
        ),
    ]
