# Generated by Django 5.2.14 on 2026-05-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bairro',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='divisao',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='divisao',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade.bairro'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endereco',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='secretario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='divisao',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade.secretaria'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidade',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade.divisao'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidade.endereco'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gerenciada_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidade',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bairro',
            index=models.Index(fields=['-created_at'], name='unidade_bai_created_819105_idx'),
        ),
        migrations.AddIndex(
            model_name='bairro',
            index=models.Index(fields=['active', 'visible'], name='unidade_bai_active_aa58a8_idx'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['-created_at'], name='unidade_end_created_73418a_idx'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['active', 'visible'], name='unidade_end_active_f74a34_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaria',
            index=models.Index(fields=['-created_at'], name='unidade_sec_created_751d96_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaria',
            index=models.Index(fields=['active', 'visible'], name='unidade_sec_active_670aae_idx'),
        ),
        migrations.AddIndex(
            model_name='divisao',
            index=models.Index(fields=['-created_at'], name='unidade_div_created_082eda_idx'),
        ),
        migrations.AddIndex(
            model_name='divisao',
            index=models.Index(fields=['active', 'visible'], name='unidade_div_active_c91277_idx'),
        ),
        migrations.AddConstraint(
            model_name='divisao',
            constraint=models.UniqueConstraint(fields=('sigla', 'secretaria'), name='unique_sigla_por_secretaria'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['-created_at'], name='unidade_uni_created_b0ebeb_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['active', 'visible'], name='unidade_uni_active_7d7e78_idx'),
        ),
    ]
