# Generated by Django 5.2.14 on 2026-05-15 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='cor',
            field=models.CharField(default='#5b5e68', help_text='Cor hex pra UI (ex: #dc2626)', max_length=7),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisoes', to='unidade.secretaria'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='unidade.bairro'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='secretario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secretarias_chefiadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='unidade.divisao'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='unidade.endereco'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_gerenciadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
