# Generated by Django 5.2.14 on 2026-05-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0003_endereco_cep_secretaria_cor_alter_divisao_secretaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='cor',
            field=models.CharField(default='#E3E728', help_text='Cor hex pra UI (ex: #dc2626)', max_length=7),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
