# Generated by Django 5.2.14 on 2026-05-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0005_seed_secretarias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='sigla',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
