# Generated by Django 5.2.14 on 2026-05-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0006_alter_divisao_sigla_alter_secretaria_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='sigla',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
