# Generated by Django 5.2.14 on 2026-05-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0007_alter_divisao_sigla'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='divisao',
            name='unique_sigla_por_secretaria',
        ),
    ]
