# Generated by Django 5.2.14 on 2026-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0008_remove_divisao_unique_sigla_por_secretaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='sigla',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
