# Generated by Django 5.2.14 on 2026-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0009_alter_divisao_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='sigla',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
