# Generated by Django 5.2.14 on 2026-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0013_seed_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='geo_precisao',
            field=models.CharField(choices=[('exato', 'Exato (rua/número)'), ('bairro', 'Aproximado (centro do bairro)'), ('centro', 'Genérico (centro da cidade)'), ('manual', 'Ajustado manualmente')], default='exato', max_length=10),
        ),
    ]
