# Generated by Django 5.2.14 on 2026-06-11 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0014_endereco_geo_precisao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='predio', to='unidade.endereco')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantaAndar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('andar', models.IntegerField(help_text='0=térreo, 1=superior, …')),
                ('nome', models.CharField(blank=True, help_text='Ex: Térreo, Superior', max_length=60)),
                ('imagem', models.ImageField(upload_to='plantas/')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='unidade.predio')),
            ],
            options={
                'ordering': ['andar'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=100)),
                ('pos_x', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pos_y', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('largura', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='unidade.plantaandar')),
                ('unidades', models.ManyToManyField(blank=True, related_name='salas', to='unidade.unidade')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='predio',
            index=models.Index(fields=['-created_at'], name='unidade_pre_created_824c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='predio',
            index=models.Index(fields=['active', 'visible'], name='unidade_pre_active_0856cc_idx'),
        ),
        migrations.AddIndex(
            model_name='plantaandar',
            index=models.Index(fields=['-created_at'], name='unidade_pla_created_d01d35_idx'),
        ),
        migrations.AddIndex(
            model_name='plantaandar',
            index=models.Index(fields=['active', 'visible'], name='unidade_pla_active_e546e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='plantaandar',
            constraint=models.UniqueConstraint(fields=('predio', 'andar'), name='unique_andar_por_predio'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['-created_at'], name='unidade_sal_created_17f72c_idx'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['active', 'visible'], name='unidade_sal_active_e050a7_idx'),
        ),
    ]
