# Generated by Django 5.2.14 on 2026-06-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0015_predio_plantaandar_sala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='unidades',
        ),
        migrations.AddField(
            model_name='sala',
            name='divisao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas', to='unidade.divisao'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='label',
            field=models.CharField(blank=True, help_text='Opcional — só pra salas sem divisão (recepção, copa…)', max_length=100),
        ),
    ]
