# Generated by Django 5.2.14 on 2026-06-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0016_remove_sala_unidades_sala_divisao_alter_sala_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='largura',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='pos_y',
        ),
        migrations.AddField(
            model_name='sala',
            name='pontos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
